TOP_50_STOCKS = [
    'RELIANCE', 'HDFCBANK', 'ICICIBANK', 'INFY', 'TCS', 
    'ITC', 'LT', 'SBIN', 'BHARTIARTL', 'BAJFINANCE',
    'AXISBANK', 'KOTAKBANK', 'ASIANPAINT', 'M&M', 'MARUTI',
    'SUNPHARMA', 'TITAN', 'HUL', 'TATASTEEL', 'ULTRACEMCO',
    'TATAMOTORS', 'NTPC', 'POWERGRID', 'HCLTECH', 'BAJAJFINSV',
    'WIPRO', 'NESTLEIND', 'ONGC', 'TECHM', 'INDUSINDBK',
    'JSWSTEEL', 'HDFCLIFE', 'GRASIM', 'COALINDIA', 'DRREDDY',
    'TATACONSUM', 'ADANIPORTS', 'CIPLA', 'APOLLOHOSP', 'EICHERMOT',
    'DIVISLAB', 'SBILIFE', 'BRITANNIA', 'BAJAJ-AUTO', 'HEROMOTOCO',
    'LTIM', 'BPCL', 'ADANIENT', 'HINDALCO', 'SHREECEM'
]
